### ISSUE TITLE
Min the JS

### ISSUE THREAD

**Issue by lilianm** [nestorInc/jukebox#89]
Minimize all js in one file. 
Add versionning for cache ?

**Comment by beuiot** [comment]
it is already minified if I'm not mistaken?
only skin .js is separate, by design.

**Comment by TiTi** [comment]
Yep already minified (unless url contains /src or #debug) for jukebox part.
But more files are loaded in fact (for PROD, not DEBUG) :
* lib/
  * domReady.min.js
  * libs.min.js
  * prototype.js
  * require.min.js
  * soundmanager2-nodebug-jsmin.js
* jukebox.min.js
* skins.min.js

A few words:
- require.min.js is actually the only file loaded from html with a `<script>` tag generated by server
- libs.min.js contains scriptaculous or prototype modules (or self module for fileuploader).
Thoses are external librairies. We've never wrote a single line of thoses files. It makes sens to concat. them.
- prototype.js was put aside because bigger and mostly because (as said in Gruntfile.js)
  - prototypejs website doesn't provide a minified version
  - [minification by grunt/uglifyjs] doesn't works :( [minify too much stuff]
- domReady.min.js is a require.min.js plugin if I recall
- soundmanager2 might be removed in case we switch to manual html5 audio handling

This split is good, especially since the cache system.
Because we often update jukebox.min.js, but never prototype.js for instance.
**Therefore, it allows browser to cache files and only redownload updated ones!**
If we put everything in a single file, it forces clients to redownload prototype.js (and all other files) even thought they haven't changed...

Prototype.js is now available in version 1.7.3 (we're in 1.7), but still doesn't provide a minified version. So no easy improvement...

I'm open to discuss merging skins.min.js and jukebox.min.js for instance, but I think it's better the way it is right now.
